apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: dev
  project: default
  source:
    path: yamls
    repoURL: https://github.com/aka-devops/argocd-demo
    targetRevision: HEAD
